name: hashchecker_web
description: Ssoda web service.

publish_to: 'none'

version: 2.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0
  fluro: ^2.0.3
  http: ^0.13.3
  intl: ^0.17.0
  url_strategy: ^0.2.0
  loading_overlay: ^0.3.0
  animated_text_kit: ^4.2.1
  dio: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  animations: ^2.0.1
  flash: ^2.0.1
  flutter_fortune_wheel: ^1.1.0
  url_launcher: ^6.0.10
  google_fonts: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/home/

  uses-material-design: true
